# Generated by Django 6.1.1 on 2026-09-14 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('category', models.CharField(max_length=50, verbose_name='카테고리')),
                ('visitor_count', models.IntegerField(default=0, verbose_name='방문자 수')),
                ('sales_amount', models.IntegerField(default=0, verbose_name='매출액')),
            ],
        ),
    ]
