create database mbasic;

use MBASIC;

CREATE TABLE MVCBOARD1 (
BNO INT PRIMARY KEY AUTO_INCREMENT,
BNAME VARCHAR(200) NOT NULL,
BPASS VARCHAR(50) NOT NULL,
BTITLE VARCHAR(1000) NOT NULL,
BCONTENT TEXT NOT NULL,
BDATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
BHIT INT NOT NULL DEFAULT 0,
BIP VARCHAR(50) NOT NULL
);

DESC MVCBOARD1;

INSERT INTO MVCBOARD1 
(BNO, BNAME, BPASS, BTITLE, BCONTENT, BIP)
VALUE (
1, '홍길동', '1234', '첫번째 글쓰기', '이것은 첫번째로 쓴 글의 내용입니다.',
'168.192.0.4'
);
INSERT INTO MVCBOARD1 
(BNO, BNAME, BPASS, BTITLE, BCONTENT, BIP)
VALUE (
2, '가길동', '1234', '두번째 글쓰기', '이것은 두번째로 쓴 글의 내용입니다.',
'168.192.0.4'
);
INSERT INTO MVCBOARD1 
(BNAME, BPASS, BTITLE, BCONTENT, BIP)
VALUE (
'오길동', '1234', '네번째 글쓰기', '이것은 네번째로 쓴 글의 내용입니다.',
'168.192.0.4'
);

SELECT * FROM MVCBOARD1;

SELECT (SELECT COUNT(*) `CNT` FROM MVCBOARD1), BNO, BNAME, BTITLE, BCONTENT, BDATE, BHIT FROM MVCBOARD1 ORDER BY BDATE DESC;

SELECT ROW_NUMBER() OVER (ORDER BY BNO ASC) AS ROWNUM, BNO, BNAME, BTITLE, BCONTENT, BDATE, BHIT FROM MVCBOARD1 ORDER BY BDATE DESC;